export const GET_LIST_CAR_SUCCESS="GET_LIST_CAR_SUCCESS";
export const GET_LIST_CAR_ERR="GET_LIST_CAR_ERR";
export const PUT_SEAT="PUT_SEAT";
export const PUT_NULL="PUT_NULL";
export const SIGN_UP_SUCCESS="SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED="SIGN_UP_FAILED";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILED="LOGIN_FAILED";
export const SET_TOKEN="SET_TOKEN";
export const DEL_TOKEN="DEL_TOKEN";
export const SET_START_LOCATION="SET_START_LOCATION";
export const DEL_START_LOCATION="DEL_START_LOCATION";
export const SET_END_LOCATION="SET_END_LOCATION";
export const DEL_END_LOCATION="DEL_END_LOCATION";
export const PUT_CAR="PUT_CAR";
export const DEL_CAR="DEL_CAR";
export const SAVE_TICKET="SAVE_TICKET";
export const UNSAVE_TICKET="UNSAVE_TICKET";
export const PUT_TICKET_SUCCESS="PUT_TICKET_SUCCESS";
export const PUT_TICKET_FAILED="PUT_TICKET_FAILED";
export const SEND_MAIL_SUCESS="SEND_MAIL_SUCESS";
export const SEND_MAIL_FAIL="SEND_MAIL_FAIL";
export const SEARCH_TICKET_SUCCESS="SEARCH_TICKET_SUCCESS";
export const SEARCH_TICKET_FAIL="SEARCH_TICKET_FAIL";
export const CANCEL_TICKET_SUCCESS="CANCEL_TICKET_SUCCESS";
export const CANCEL_TICKET_FAIL="CANCEL_TICKET_FAIL";





export const URL_API=`https://api-serivice-vexe.herokuapp.com/api`;
export const URL_API_LOCAL=`http://localhost:8080/api`;
